name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Node.js környezet beállítása
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Deploy FTP-re
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER1 }}
          username: ${{ secrets.FTP_USERNAME1 }}
          password: ${{ secrets.FTP_PASSWORD1 }}
          local-dir: ./
          server-dir: /public_html/pizzeria/
